# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160604_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubToipc',
            new_name='SubTopic',
        ),
    ]
