# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160604_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
