# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160618_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='club',
        ),
    ]
