# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_subtopic_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Club'),
            preserve_default=False,
        ),
    ]
