# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_subtopic_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
