# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160624_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='heading',
            field=models.CharField(max_length=40),
        ),
    ]
